import { NextResponse } from "next/server";
import { writeFile } from "fs/promises";
import { join } from "path";
import prisma from "@/lib/prisma";

const SITE_URL =
    process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") || "https://example.com";

/**
 * POST /api/admin/generate-sitemap
 * Generates public/sitemap.xml and public/robots.txt from the database.
 */
export async function POST() {
    try {
        // ── 1. Static pages from PageMeta (only published) ─────────────────────
        const pages = await prisma.pageMeta.findMany({
            where: { published: true },
            select: { slug: true, updatedAt: true },
            orderBy: { slug: "asc" },
        });

        // ── 2. Dynamic rooms ────────────────────────────────────────────────────
        const rooms = await prisma.room.findMany({
            where: { published: true },
            select: { slug: true, updatedAt: true },
            orderBy: { order: "asc" },
        });

        // ── 3. Dynamic POIs ─────────────────────────────────────────────────────
        const pois = await prisma.poi.findMany({
            select: { slug: true, updatedAt: true },
            orderBy: { order: "asc" },
        });

        // ── 4. Legal pages (raw SQL — legalPage not typed in generated client) ──
        const legalPages = await prisma.$queryRaw<{ slug: string; updatedAt: Date }[]>`
            SELECT slug, updatedAt FROM legal_pages ORDER BY \`order\` ASC
        `;

        // ── Build URL entries ───────────────────────────────────────────────────
        type UrlEntry = {
            loc: string;
            lastmod: string;
            changefreq: string;
            priority: string;
        };

        const urls: UrlEntry[] = [];

        // Static pages
        for (const page of pages) {
            const path = page.slug === "home" ? "" : `/${page.slug}`;
            urls.push({
                loc: `${SITE_URL}${path}`,
                lastmod: page.updatedAt.toISOString().split("T")[0],
                changefreq: page.slug === "home" ? "weekly" : "monthly",
                priority: page.slug === "home" ? "1.0" : "0.8",
            });
        }

        // Room pages
        for (const room of rooms) {
            urls.push({
                loc: `${SITE_URL}/rooms/${room.slug}`,
                lastmod: room.updatedAt.toISOString().split("T")[0],
                changefreq: "monthly",
                priority: "0.7",
            });
        }

        // POI pages
        for (const poi of pois) {
            urls.push({
                loc: `${SITE_URL}/athens/${poi.slug}`,
                lastmod: poi.updatedAt.toISOString().split("T")[0],
                changefreq: "monthly",
                priority: "0.6",
            });
        }

        // Legal pages
        for (const legal of legalPages) {
            urls.push({
                loc: `${SITE_URL}/legal/${legal.slug}`,
                lastmod: legal.updatedAt.toISOString().split("T")[0],
                changefreq: "yearly",
                priority: "0.3",
            });
        }

        // ── Build sitemap.xml ───────────────────────────────────────────────────
        const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
    .map(
        (u) => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${u.lastmod}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`
    )
    .join("\n")}
</urlset>`;

        // ── Build robots.txt ────────────────────────────────────────────────────
        const robotsTxt = `# robots.txt — generated by The Frogs Admin
User-agent: *
Allow: /

# Block admin area
Disallow: /admin/

Sitemap: ${SITE_URL}/sitemap.xml
`;

        // ── Write files to public/ ──────────────────────────────────────────────
        const publicDir = join(process.cwd(), "public");
        await Promise.all([
            writeFile(join(publicDir, "sitemap.xml"), sitemapXml, "utf-8"),
            writeFile(join(publicDir, "robots.txt"), robotsTxt, "utf-8"),
        ]);

        return NextResponse.json({
            success: true,
            urlCount: urls.length,
            message: `Generated sitemap.xml (${urls.length} URLs) and robots.txt`,
        });
    } catch (err: any) {
        console.error("[generate-sitemap] Error:", err);
        return NextResponse.json(
            { success: false, error: err?.message || "Unknown error" },
            { status: 500 }
        );
    }
}
